[package]
name = "mediaprobe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
h264-reader = "0.6.0"
mediabox = { path = "../mediabox" }
tokio = { version = "1.23.0", features = ["macros", "rt", "rt-multi-thread"] }
xflags = "0.3.1"
